In [3]:
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import sklearn
import sys
import tensorflow as tf
import time
from PIL import Image

from tensorflow import keras
from tensorflow.keras.preprocessing import image
print(tf.__version__)

2.1.0


## 最简单的FC层

In [249]:
k=np.array([2.,2.])
b=np.array([1.,1.])
b.reshape([2,1]).shape

(2, 1)

In [250]:
k_init1 = tf.constant_initializer(k.reshape([1,2]))
b_init1 = tf.constant_initializer(b.reshape([2,1]))

In [251]:
k_init = tf.constant_initializer(2)
b_init = tf.constant_initializer(1)

In [252]:
inputs = tf.reshape(tf.constant([[1., 2.], [2., 3.]]), shape=[4, 1])
layer = keras.layers.Dense(2, kernel_initializer=k_init1, bias_initializer=b_init1)
outputs = layer(inputs)
outputs

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[3., 3.],
       [5., 5.],
       [5., 5.],
       [7., 7.]], dtype=float32)>

## 矩阵乘积

In [265]:
a = [[1.],[2.], [2.], [3.]] #input

In [266]:
b = [[2.,2.]] #kernel

In [267]:
c = [[1.,1.]] #bias

In [268]:
np.dot(a,b)+c1

array([[3., 3.],
       [5., 5.],
       [5., 5.],
       [7., 7.]])

### 更简单的矩阵点乘

In [269]:
W = tf.ones(shape=(2, 2))
b = tf.zeros(shape=(2))

@tf.function
def forward(x):
    return W * x + b


out_a = forward([1, 0])
print(out_a)

out_b = forward([0,1])
print(out_b)

tf.Tensor(
[[1. 0.]
 [1. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 1.]
 [0. 1.]], shape=(2, 2), dtype=float32)
