In [1]:
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import sklearn
import sys
import tensorflow as tf
import time
from PIL import Image

from tensorflow import keras
from tensorflow.keras.preprocessing import image
print(tf.__version__)

2.1.0


In [230]:
x = np.array([[1., -0.5],[1., -0.6],[1., -0.7]],dtype='float32')    #(3,2)
k = np.array([[-0.1, 0.3, 0.5], [-0.2, 0.4, 0.6]],dtype='float32') #(2,3)
b = np.array([[0.1, 0.2, -0.3]],dtype='float32')  #(1,3)

In [231]:
k_init = tf.constant_initializer(k)
b_init = tf.constant_initializer(b)

In [256]:
layer = keras.layers.Dense(3, kernel_initializer= k_init, bias_initializer=b_init)
y = layer(x)

In [258]:
output = tf.nn.relu(y)
output

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.1       , 0.3       , 0.        ],
       [0.12      , 0.26      , 0.        ],
       [0.14      , 0.22000001, 0.        ]], dtype=float32)>

## 设定激活函数(Relu)

In [268]:
layer = keras.layers.Dense(3, activation= 'sigmoid', kernel_initializer=k_init, bias_initializer=b_init)
outputs = layer(x)
outputs

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.5249792 , 0.5744425 , 0.4750208 ],
       [0.529964  , 0.5646363 , 0.4600851 ],
       [0.5349429 , 0.55477923, 0.44522074]], dtype=float32)>

## 矩阵乘积

In [263]:
x = np.array([[1., -0.5],[1., -0.6],[1., -0.7]],dtype='float32')    #(3,2)
k = np.array([[-0.1, 0.3, 0.5], [-0.2, 0.4, 0.6]],dtype='float32') #(2,3)
b = np.array([[0.1, 0.2, -0.3]],dtype='float32')  #(1,3)

In [264]:
y = np.dot(x,k)+b    #Dense

In [265]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [266]:
sigmoid(y)

array([[0.5249792 , 0.5744425 , 0.4750208 ],
       [0.529964  , 0.5646363 , 0.4600851 ],
       [0.5349429 , 0.55477923, 0.44522074]], dtype=float32)