In [1]:
# http://www.telesens.co/2018/04/09/initializing-weights-for-the-convolutional-and-fully-connected-layers/

from scipy import signal
from scipy import misc
import numpy as np
from numpy import zeros

In [2]:
def unfold_matrix(X, k):
    n, m = X.shape[0:2]
    xx = zeros(((n - k + 1) * (m - k + 1), k**2))
    row_num = 0
    def make_row(x):
        return x.flatten()

    for i in range(n- k+ 1):
        for j in range(m - k + 1):
            #collect block of m*m elements and convert to row
            xx[row_num,:] = make_row(X[i:i+k, j:j+k])
            row_num = row_num + 1

    return xx

In [13]:
w =  np.array([1,-1,1,0,-1,0,0,1,0]).astype("float32").reshape(3,3)

In [14]:
x = np.arange(25).reshape(5,5)

In [15]:
n, m = x.shape[0:2]

In [16]:
print(n,m)

5 5


In [17]:
k = w.shape[0]
k

3

In [37]:
y = signal.correlate2d(x, w, mode='full')
y

array([[  0.,   0.,   1.,   2.,   3.,   4.,   0.],
       [  0.,   5.,   5.,   5.,   5.,   5.,   0.],
       [  0.,   6.,   6.,   7.,   8.,   4.,   4.],
       [  5.,   6.,  11.,  12.,  13.,   4.,   9.],
       [ 10.,   6.,  16.,  17.,  18.,   4.,  14.],
       [ 15., -19.,  -5.,  -5.,  -5., -25.,  19.],
       [ 20.,   1.,  21.,  22.,  23.,  -1.,  24.]])

In [36]:
x_unfolded = unfold_matrix(x, 3)
x_unfolded

array([[ 0.,  1.,  2.,  5.,  6.,  7., 10., 11., 12.],
       [ 1.,  2.,  3.,  6.,  7.,  8., 11., 12., 13.],
       [ 2.,  3.,  4.,  7.,  8.,  9., 12., 13., 14.],
       [ 5.,  6.,  7., 10., 11., 12., 15., 16., 17.],
       [ 6.,  7.,  8., 11., 12., 13., 16., 17., 18.],
       [ 7.,  8.,  9., 12., 13., 14., 17., 18., 19.],
       [10., 11., 12., 15., 16., 17., 20., 21., 22.],
       [11., 12., 13., 16., 17., 18., 21., 22., 23.],
       [12., 13., 14., 17., 18., 19., 22., 23., 24.]])

In [22]:
w_flat = w.flatten()
w_flat

array([ 1., -1.,  1.,  0., -1.,  0.,  0.,  1.,  0.], dtype=float32)

In [30]:
yy = np.dot(x_unfolded, w_flat)
yy

array([ 6.,  7.,  8., 11., 12., 13., 16., 17., 18.])

In [26]:
yy = yy.reshape((n-k+1, m-k+1))
print(yy)

[[ 6.  7.  8.]
 [11. 12. 13.]
 [16. 17. 18.]]
